# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/imports/xilinx_pcie4_uscale_plus_x0y2.xdc

# IP: ip/pcie4_uscale_plus_1/pcie4_uscale_plus_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_1 || ORIG_REF_NAME==pcie4_uscale_plus_1} -quiet] -quiet
