# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableLutRouteBelPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableUnconnectedCarry8PinPower 1
create_project -in_memory -part xcku15p-ffve1517-3-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/pcie4_uscale_plus_1_ex.cache/wt [current_project]
set_property parent.project_path /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/pcie4_uscale_plus_1_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/pcie4_uscale_plus_1_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/imports/ep_mem.v
  /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/imports/pcie_app_uscale.v
  /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/imports/pio.v
  /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/imports/pio_ep.v
  /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/imports/pio_ep_mem_access.v
  /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/imports/pio_intr_ctrl.v
  /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/imports/pio_rx_engine.v
  /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/imports/pio_to_ctrl.v
  /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/imports/pio_tx_engine.v
  /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/imports/xilinx_pcie4_uscale_ep.v
}
read_ip -quiet /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/pcie4_uscale_plus_1_ex.srcs/sources_1/ip/pcie4_uscale_plus_1/pcie4_uscale_plus_1.xci
set_property used_in_implementation false [get_files -all /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/pcie4_uscale_plus_1_ex.srcs/sources_1/ip/pcie4_uscale_plus_1/ip_0/synth/pcie4_uscale_plus_1_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/pcie4_uscale_plus_1_ex.srcs/sources_1/ip/pcie4_uscale_plus_1/ip_0/synth/pcie4_uscale_plus_1_gt.xdc]
set_property used_in_implementation false [get_files -all /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/pcie4_uscale_plus_1_ex.srcs/sources_1/ip/pcie4_uscale_plus_1/pcie4_uscale_plus_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/pcie4_uscale_plus_1_ex.srcs/sources_1/ip/pcie4_uscale_plus_1/synth/pcie4_uscale_plus_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/pcie4_uscale_plus_1_ex.srcs/sources_1/ip/pcie4_uscale_plus_1/synth/pcie4_uscale_plus_1_late.xdc]
set_property used_in_implementation false [get_files -all /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/pcie4_uscale_plus_1_ex.srcs/sources_1/ip/pcie4_uscale_plus_1/source/ip_pcie4_uscale_plus_x0y2.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/imports/xilinx_pcie4_uscale_plus_x0y2.xdc
set_property used_in_implementation false [get_files /home/chiwei/work/checkout/xilinx-bali.git.new/xilinx_ip/pcie4_uscale_plus_1_ex/imports/xilinx_pcie4_uscale_plus_x0y2.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top xilinx_pcie4_uscale_ep -part xcku15p-ffve1517-3-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xilinx_pcie4_uscale_ep.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file xilinx_pcie4_uscale_ep_utilization_synth.rpt -pb xilinx_pcie4_uscale_ep_utilization_synth.pb"
