#!/usr/bin/env python2
# DAL Register Utility

# NOTE: This file was generated by '/home/chiwei/work/checkout/pld_new/common/vi_scripts/vgen.py' - DO NOT EDIT -
#          - 2017-05-16 09:22:29 -


# Bitfield Definitions
bitfields = {
	'bist/pcie/csr/status11' : {
		0xffffffff00000000: 'iterations',
		0x0000000000000001: 'run_dyn'
        },
	'bist/pcie/csr/status10' : {
		0xffffffff00000000: 'iterations',
		0x0000000000000001: 'run_dyn'
        },
	'bist/pcie/csr/status8' : {
		0xffffffff00000000: 'iterations',
		0x0000000000000001: 'run_dyn'
        },
	'bist/pcie/csr/test_reg' : {
		0xffffffffffffffff: 'test_reg'
        },
	'bist/pcie/csr/status9' : {
		0xffffffff00000000: 'iterations',
		0x0000000000000001: 'run_dyn'
        },
	'bist/pcie/csr/status6' : {
		0xffffffff00000000: 'iterations',
		0x0000000000000001: 'run_dyn'
        },
	'bist/pcie/csr/status7' : {
		0xffffffff00000000: 'iterations',
		0x0000000000000001: 'run_dyn'
        },
	'bist/pcie/csr/ctrl' : {
		0xffffffff00000000: 'iterations',
		0x000000000fff0000: 'link_en',
		0x000000000000fff0: 'pat_type',
		0x0000000000000001: 'run'
        },
	'bist/pcie/csr/status5' : {
		0xffffffff00000000: 'iterations',
		0x0000000000000001: 'run_dyn'
        },
	'bist/pcie/csr/status4' : {
		0xffffffff00000000: 'iterations',
		0x0000000000000001: 'run_dyn'
        },
	'bist/pcie/csr/status3' : {
		0xffffffff00000000: 'iterations',
		0x0000000000000001: 'run_dyn'
        },
	'bist/pcie/csr/status2' : {
		0xffffffff00000000: 'iterations',
		0x0000000000000001: 'run_dyn'
        },
	'bist/pcie/csr/status1' : {
		0xffffffff00000000: 'iterations',
		0x0000000000000001: 'run_dyn'
        },
	'bist/pcie/csr/status0' : {
		0xffffffff00000000: 'iterations',
		0x0000000000000001: 'run_dyn'
        },
	'link/ch/fc1_layer_kr/dec_exception' : {
		0x0000000000000008: 'CSR_STAT_BLOCK_LOCK',
		0x0000000000000004: 'CSR_EXPT_LOSS_BLOCKLOCK',
		0x0000000000000002: 'CSR_STAT_FEC_LOCK',
		0x0000000000000001: 'CSR_EXPT_FEC_LOCK_TO'
        },
	'link/ch/fc1_layer_kr/_scratch' : {
		0xffffffffffffffff: 'scratch'
        },
	'link/ch/fc1_layer_kr/enc_config' : {
		0x0000000000000010: 'CSR_PCS_ENC_INV',
		0x0000000000000008: 'CSR_PCS_ENC_FEC_ENA',
		0x0000000000000004: 'CSR_PCS_SCRAMB_DIS',
		0x0000000000000002: 'CSR_ENC_OUT_ENDIAN_SWAP',
		0x0000000000000001: 'CSR_ENC_IN_ENDIAN_SWAP'
        },
	'link/ch/fc1_layer_kr/dec_config' : {
		0x0000000000000040: 'CSR_DEC_DESCRAM_OUT_ENDIAN_SWAP',
		0x0000000000000020: 'CSR_DEC_DESCRAM_IN_ENDIAN_SWAP',
		0x0000000000000010: 'CSR_PCS_DEC_INV',
		0x0000000000000008: 'CSR_PCS_DESCRAMB_DIS',
		0x0000000000000004: 'CSR_PCS_FORCE_NO_FEC',
		0x0000000000000002: 'CSR_DEC_OUT_ENDIAN_SWAP',
		0x0000000000000001: 'CSR_DEC_IN_ENDIAN_SWAP'
        },
	'link/ch/fc1_layer_kr/dec_corr_bit_count' : {
		0x000000000000ffff: 'CSR_STAT_CORR_BIT_CNT'
        },
	'link/ch/fc1_layer_kr/dec_slip_count' : {
		0x0000000000001fff: 'CSR_STAT_SLIP_COUNT'
        },
	'link/ch/fc1_layer_kr/enc_exception' : {
		0x0000000000000002: 'CSR_EXPT_ENC_EMPT',
		0x0000000000000001: 'CSR_EXPT_ENC_FULL'
        },
	'link/ch/fc1_layer_kr/dec_corr_event_count' : {
		0x000000000000ffff: 'CSR_STAT_CORR_EVENT_CNT'
        },
	'link/ch/fc1_layer_kr/dec_uncorr_event_count' : {
		0x000000000000ffff: 'CSR_STAT_UNCORR_EVENT_CNT'
        },
	'link/g/credit_stats/CreditCounter' : {
		0x00000000ffffffff: 'credit'
        },
	'link/g/credit_stats/TimeMinCredit' : {
		0x00000000ffffffff: 'tick'
        },
	'link/g/credit_stats/CreditBBMin' : {
		0x00000000ffffffff: 'credit'
        },
	'link/g/credit_stats/_scratch' : {
		0xffffffffffffffff: 'scratch'
        },
	'link/g/credit_stats/CreditBBMax' : {
		0x00000000ffffffff: 'credit'
        },
	'link/g/credit_stats/CreditStart' : {
		0x00000000ffffffff: 'credit'
        },
	'global/g/clkrst/ClkCtrSerdes6_1' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes6_0' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes1_0' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes1_1' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes0_1' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes0_0' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrTxBist' : {
		0x0000000000ffffff: 'ClkCtrTxBist'
        },
	'global/g/clkrst/ClkCtrPcie' : {
		0x0000000000ffffff: 'ClkCtrPcie'
        },
	'global/g/clkrst/ClkCtrSerdes7_1' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes7_0' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrFcCore' : {
		0x0000000000ffffff: 'ClkCtrFcCore'
        },
	'global/g/clkrst/RstStatus' : {
		0x0000000000000010: 'PllFcCoreLocked',
		0x0000000000000001: 'ChipStatus'
        },
	'global/g/clkrst/ClkCtrSerdes5_0' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes5_1' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes4_1' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes4_0' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes8_1' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes8_0' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes3_0' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes3_1' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrCtrl' : {
		0x0000000000000001: 'LatchAndRst'
        },
	'global/g/clkrst/ClkCtrSerdes2_1' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes2_0' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/TxBistCtrl' : {
		0x0000000000000003: 'LinkSpeed'
        },
	'global/g/clkrst/_scratch' : {
		0xffffffffffffffff: '_scratch'
        },
	'global/g/clkrst/TxBistStatus' : {
		0x0000000000000001: 'PllLock'
        },
	'global/g/clkrst/ClkCtrSerdes9_0' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes9_1' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes11_0' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes11_1' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes10_1' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/ClkCtrSerdes10_0' : {
		0x00ffffff00000000: 'TxClk',
		0x0000000000ffffff: 'RxRecClk'
        },
	'global/g/clkrst/RstCtrl_0' : {
		0x00000000001fff00: 'LinkRst',
		0x0000000000000010: 'PllFcCoreRst',
		0x0000000000000004: 'GlbTimestampRst',
		0x0000000000000002: 'PllXbarRst',
		0x0000000000000001: 'ChipRst'
        },
	'global/g/clkrst/RstCtrl_1' : {
		0x0fff000000000000: 'LinkPcieRst',
		0x00000fff00000000: 'LinkFcCoreRst',
		0x000000001fff0000: 'LinkSerdesTxRst',
		0x0000000000001fff: 'LinkSerdesRxRst'
        },
	'global/g/clkrst/ClkCtrXbar' : {
		0x0000000000ffffff: 'ClkCtrXbar'
        },
	'link/ch/serdes/PrbsRxCnt' : {
		0x0000ffffffffffff: 'PrbsRxCnt'
        },
	'link/ch/serdes/PrbsLock' : {
		0x0000000000000001: 'PrbsLock'
        },
	'link/ch/serdes/RxData' : {
		0x000000ffffffffff: 'RxData'
        },
	'link/ch/serdes/PrbsErrCnt' : {
		0x000000000000ffff: 'PrbsErrCnt'
        },
	'link/ch/serdes/TxData' : {
		0x000000ffffffffff: 'RxData'
        },
	'link/ch/serdes/Status' : {
		0x0000000000020000: 'PLLLocked_425',
		0x0000000000010000: 'PLLLocked_219',
		0x0000000000007000: 'LinkSpeed',
		0x0000000000000800: 'TxReady',
		0x0000000000000400: 'RxReady',
		0x0000000000000100: 'RxCalBusy',
		0x0000000000000080: 'TxCalBusy',
		0x0000000000000040: 'RxLockedToData',
		0x0000000000000020: 'RxLockedToRef',
		0x0000000000000010: 'RxAnalogRst',
		0x0000000000000008: 'RxDigitalRst',
		0x0000000000000004: 'TxAnalogRst',
		0x0000000000000002: 'TxDigitalRst',
		0x0000000000000001: 'PLLPwrDn'
        },
	'link/ch/serdes/PrbsInjErrCnt' : {
		0x000000000000ffff: 'PrbsInjErrCnt'
        },
	'link/ch/serdes/PrbsNotLockedCnt' : {
		0x00000000ffffffff: 'PrbsNotLockedCnt'
        },
	'link/ch/serdes/_scratch' : {
		0xffffffffffffffff: 'scratch'
        },
	'link/ch/serdes/Ctl' : {
		0x0000000000000400: 'CDRLockOverride',
		0x0000000000000200: 'RxInvert',
		0x0000000000000100: 'TxInvert',
		0x0000000000000080: 'EyeVClear',
		0x0000000000000040: 'EyeHClear',
		0x0000000000000020: 'TxMuxSel',
		0x0000000000000018: 'CDRLockMode',
		0x0000000000000004: 'SerialLpbkEn',
		0x0000000000000002: 'RxReset',
		0x0000000000000001: 'TxReset'
        },
	'link/ch/serdes/PrbsCtl' : {
		0x0000000000000020: 'NotLockedCntClr',
		0x0000000000000010: 'RxCntClr',
		0x0000000000000008: 'ErrCntClr',
		0x0000000000000004: 'InjErr',
		0x0000000000000003: 'PrbsSel'
        },
	'link/g/csr/InvlStatStop' : {
		0x0000000000000004: 'TooSoon',
		0x0000000000000002: 'Underflow',
		0x0000000000000001: 'Overflow'
        },
	'link/g/csr/LinkStatus' : {
		0x0000000080000000: 'CH1_REG_TSFIFOSTAT_UNDERFLOW',
		0x0000000040000000: 'CH1_REG_TSFIFOSTAT_OVERFLOW',
		0x000000001f000000: 'CH1_REG_TSFIFOSTAT_WORDS',
		0x0000000000800000: 'CH0_REG_TSFIFOSTAT_UNDERFLOW',
		0x0000000000400000: 'CH0_REG_TSFIFOSTAT_OVERFLOW',
		0x00000000001f0000: 'CH0_REG_TSFIFOSTAT_WORDS',
		0x0000000000002000: 'DroppingCh1',
		0x0000000000001000: 'DroppingCh0',
		0x0000000000000200: 'LosigCh1',
		0x0000000000000100: 'LosyncCh1',
		0x0000000000000020: 'LosigCh0',
		0x0000000000000010: 'LosyncCh0',
		0x000000000000000f: 'LinkSpeed'
        },
	'link/g/csr/TaDalZeroCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/g/csr/DataLinkFifoLevel' : {
		0x0000000000001fff: 'Words'
        },
	'link/g/csr/InvlDropCtr' : {
		0x00000000000000ff: 'count'
        },
	'link/g/csr/DataLinkFifoStat' : {
		0x0000000000020000: 'Underflow',
		0x0000000000010000: 'Overflow',
		0x0000000000001fff: 'Words'
        },
	'link/g/csr/_scratch' : {
		0xffffffffffffffff: 'scratch'
        },
	'link/g/csr/TaDalDataCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/g/csr/LinkFlush' : {
		0x0000000000000001: 'Done'
        },
	'link/g/csr/TaFifoStop' : {
		0x0000000000000020: 'InvlUnderflow',
		0x0000000000000010: 'InvlOverflow',
		0x0000000000000008: 'Ch1Underflow',
		0x0000000000000004: 'Ch1Overflow',
		0x0000000000000002: 'Ch0Underflow',
		0x0000000000000001: 'Ch0Overflow'
        },
	'link/g/csr/LinkCtrl' : {
		0x0000000000000f00: 'MonitorMode',
		0x0000000000000020: 'ScrmEnbl',
		0x0000000000000010: 'RateSel',
		0x000000000000000f: 'LinkSpeed'
        },
	'link/g/csr/TaDalStatCtr' : {
		0x00000000ffffffff: 'count'
        },
	'global/g/rcfg/PMA_PhyChanAddr' : {
		0x00000000000003ff: 'PMA_PhyChanAddr'
        },
	'global/g/rcfg/EyeQ_PhyChanAddr' : {
		0x00000000000003ff: 'EyeQ_PhyChanAddr'
        },
	'global/g/rcfg/XCVR0_PhySerialLoopback' : {
		0x00000000ffffffff: 'XCVR0_PhySerialLoopback'
        },
	'global/g/rcfg/DFE_Offset' : {
		0x000000000000003f: 'DFE_Offset'
        },
	'global/g/rcfg/XCVR1_PhySerialLoopback' : {
		0x00000000ffffffff: 'XCVR1_PhySerialLoopback'
        },
	'global/g/rcfg/Streamer_Data' : {
		0x00000000ffffffff: 'Streamer_Data'
        },
	'global/g/rcfg/XCVR1_PmaRxSignaldetect' : {
		0x00000000ffffffff: 'XCVR1_PmaRxSignaldetect'
        },
	'global/g/rcfg/PMA_ControlStatus' : {
		0x0000000000000200: 'PMA_Error',
		0x0000000000000100: 'PMA_Busy',
		0x0000000000000002: 'PMA_Read',
		0x0000000000000001: 'PMA_Write'
        },
	'global/g/rcfg/Streamer_ControlStatus' : {
		0x0000000000000200: 'Streamer_Error',
		0x0000000000000100: 'Streamer_Busy',
		0x000000000000000c: 'Streamer_Mode',
		0x0000000000000002: 'Streamer_Read',
		0x0000000000000001: 'Streamer_Write'
        },
	'global/g/rcfg/EyeQ_LogicalChanNo' : {
		0x00000000000003ff: 'EyeQ_LogicalChanNo'
        },
	'global/g/rcfg/PLL_LogicalChanNo' : {
		0x00000000000003ff: 'PLL_LogicalChanNo'
        },
	'global/g/rcfg/AEQ_ControlStatus' : {
		0x0000000000000200: 'AEQ_Error',
		0x0000000000000100: 'AEQ_Busy',
		0x0000000000000002: 'AEQ_Read',
		0x0000000000000001: 'AEQ_Write'
        },
	'global/g/rcfg/XCVR1_ResetChBitmask' : {
		0x00000000ffffffff: 'XCVR1_ResetChBitmask'
        },
	'global/g/rcfg/AEQ_LogicalChanNo' : {
		0x00000000000003ff: 'AEQ_LogicalChanNo'
        },
	'global/g/rcfg/XCVR0_PmaRxIsLockedtoref' : {
		0x00000000ffffffff: 'XCVR0_PmaRxIsLockedtoref'
        },
	'global/g/rcfg/XCVR0_ResetControl' : {
		0x0000000000000003: 'XCVR0_ResetControl'
        },
	'global/g/rcfg/PMA_LogicalChanNo' : {
		0x00000000000003ff: 'PMA_LogicalChanNo'
        },
	'global/g/rcfg/PMA_Data' : {
		0x000000000000007f: 'PMA_Data'
        },
	'global/g/rcfg/EyeQ_Data' : {
		0x000000000000ffff: 'EyeQ_Data'
        },
	'global/g/rcfg/DFE_LogicalChanNo' : {
		0x00000000000003ff: 'DFE_LogicalChanNo'
        },
	'global/g/rcfg/DFE_ControlStatus' : {
		0x0000000000000200: 'DFE_Error',
		0x0000000000000100: 'DFE_Busy',
		0x0000000000000002: 'DFE_Read',
		0x0000000000000001: 'DFE_Write'
        },
	'global/g/rcfg/DFE_PhyChanAddr' : {
		0x00000000000003ff: 'DFE_PhyChanAddr'
        },
	'global/g/rcfg/EyeQ_ControlStatus' : {
		0x0000000000000200: 'EyeQ_Error',
		0x0000000000000100: 'EyeQ_Busy',
		0x0000000000000002: 'EyeQ_Read',
		0x0000000000000001: 'EyeQ_Write'
        },
	'global/g/rcfg/XCVR1_PmaRxSetLocktodata' : {
		0x00000000ffffffff: 'XCVR1_PmaRxSetLocktodata'
        },
	'global/g/rcfg/AEQ_PhyChanAddr' : {
		0x00000000000003ff: 'AEQ_PhyChanAddr'
        },
	'global/g/rcfg/PLL_PhyChanAddr' : {
		0x00000000000003ff: 'PLL_PhyChanAddr'
        },
	'global/g/rcfg/EyeQ_Offset' : {
		0x000000000000003f: 'EyeQ_Offset'
        },
	'global/g/rcfg/Streamer_PhyChanAddr' : {
		0x00000000000003ff: 'Streamer_PhyChanAddr'
        },
	'global/g/rcfg/Streamer_Offset' : {
		0x000000000000ffff: 'Streamer_Offset'
        },
	'global/g/rcfg/ATX_ControlStatus' : {
		0x0000000000000200: 'ATX_Error',
		0x0000000000000100: 'ATX_Busy',
		0x0000000000000002: 'ATX_Read',
		0x0000000000000001: 'ATX_Write'
        },
	'global/g/rcfg/XCVR1_PmaRxSetLocktoref' : {
		0x00000000ffffffff: 'XCVR1_PmaRxSetLocktoref'
        },
	'global/g/rcfg/XCVR1_ResetControl' : {
		0x0000000000000003: 'XCVR1_ResetControl'
        },
	'global/g/rcfg/PLL_Offset' : {
		0x000000000000000f: 'PLL_Offset'
        },
	'global/g/rcfg/XCVR1_PmaRxIsLockedtodata' : {
		0x00000000ffffffff: 'XCVR1_PmaRxIsLockedtodata'
        },
	'global/g/rcfg/AEQ_Data' : {
		0x000000000000ffff: 'AEQ_Data'
        },
	'global/g/rcfg/XCVR0_PmaRxSetLocktodata' : {
		0x00000000ffffffff: 'XCVR0_PmaRxSetLocktodata'
        },
	'global/g/rcfg/PLL_Data' : {
		0x000000000000ffff: 'PLL_Data'
        },
	'global/g/rcfg/ATX_Data' : {
		0x000000000000ffff: 'ATX_Data'
        },
	'global/g/rcfg/DFE_Data' : {
		0x000000000000ffff: 'DFE_Data'
        },
	'global/g/rcfg/XCVR0_PmaRxSignaldetect' : {
		0x00000000ffffffff: 'XCVR0_PmaRxSignaldetect'
        },
	'global/g/rcfg/ATX_Offset' : {
		0x000000000000000f: 'ATX_Offset'
        },
	'global/g/rcfg/Streamer_LogicalChanNo' : {
		0x00000000000003ff: 'Streamer_LogicalChanNo'
        },
	'global/g/rcfg/AEQ_Offset' : {
		0x000000000000000f: 'AEQ_Offset'
        },
	'global/g/rcfg/XCVR0_PmaRxIsLockedtodata' : {
		0x00000000ffffffff: 'XCVR0_PmaRxIsLockedtodata'
        },
	'global/g/rcfg/ATX_LogicalChanNo' : {
		0x00000000000003ff: 'ATX_LogicalChanNo'
        },
	'global/g/rcfg/PMA_Offset' : {
		0x000000000000003f: 'PMA_Offset'
        },
	'global/g/rcfg/PLL_ControlStatus' : {
		0x0000000000000200: 'PLL_Error',
		0x0000000000000100: 'PLL_MIF_Busy',
		0x0000000000000002: 'PLL_Read',
		0x0000000000000001: 'PLL_Write'
        },
	'global/g/rcfg/XCVR0_PmaRxSetLocktoref' : {
		0x00000000ffffffff: 'XCVR0_PmaRxSetLocktoref'
        },
	'global/g/rcfg/XCVR1_PmaRxIsLockedtoref' : {
		0x00000000ffffffff: 'XCVR1_PmaRxIsLockedtoref'
        },
	'global/g/rcfg/XCVR0_ResetChBitmask' : {
		0x00000000ffffffff: 'XCVR0_ResetChBitmask'
        },
	'bist/tx_ch/txbist_crc_err_inj_cnt' : {
		0x0000ffffffffffff: 'count'
        },
	'bist/tx_ch/txbist_wr_addr' : {
		0x0000000000003fff: 'addr'
        },
	'bist/tx_ch/txbist_ram_end' : {
		0x0000000000003fff: 'ptr'
        },
	'bist/tx_ch/txbist_idle_primitive' : {
		0xffffffffffffffff: 'data'
        },
	'bist/tx_ch/txbist_rd_addr' : {
		0x0000000000003fff: 'addr'
        },
	'bist/tx_ch/txbist_tx_frame_cnt' : {
		0x0000ffffffffffff: 'count'
        },
	'bist/tx_ch/txbist_ctl' : {
		0x0000000000000400: 'sync_start',
		0x0000000000000200: 'fec_mode',
		0x0000000000000100: 'bistout_en',
		0x0000000000000080: 'control_space',
		0x0000000000000040: 'crc_err_inj',
		0x0000000000000020: 'crc_auto_en',
		0x0000000000000010: '10b_err_inj',
		0x0000000000000008: 'interval_sync_en',
		0x0000000000000007: 'mode'
        },
	'bist/tx_ch/txbist_loop_cnt' : {
		0x00000000ffffffff: 'cnt'
        },
	'bist/tx_ch/txbist_rd_data' : {
		0xffffffffffffffff: 'data'
        },
	'bist/tx_ch/txbist_reg_primitive' : {
		0xffffffffffffffff: 'data'
        },
	'bist/tx_ch/txbist_ipg_min' : {
		0x000000000000ffff: 'size'
        },
	'bist/tx_ch/txbist_wr_data' : {
		0xffffffffffffffff: 'data'
        },
	'bist/tx_ch/_scratch' : {
		0xffffffffffffffff: 'scratch'
        },
	'bist/tx_ch/txbist_tx_prim_cnt' : {
		0x0000ffffffffffff: 'count'
        },
	'bist/tx_ch/txbist_ipg_offset' : {
		0x000000000000000f: 'offset'
        },
	'pcie/g/perf/LINK6_COMPLETE_TICKS' : {
		0x00000000ffffffff: 'LINK6_COMPLETE_TICKS'
        },
	'pcie/g/perf/LINK5_VALID_TICKS' : {
		0x00000000ffffffff: 'LINK5_VALID_TICKS'
        },
	'pcie/g/perf/LINK2_REQ_TICKS' : {
		0x00000000ffffffff: 'LINK2_REQ_TICKS'
        },
	'pcie/g/perf/LINK4_COMPLETE_TICKS' : {
		0x00000000ffffffff: 'LINK4_COMPLETE_TICKS'
        },
	'pcie/g/perf/LINK3_COMPLETE_TICKS' : {
		0x00000000ffffffff: 'LINK3_COMPLETE_TICKS'
        },
	'pcie/g/perf/TX_POST_DAT_ZERO_CRED_CTR' : {
		0x000000000000ffff: 'TX_POST_DAT_ZERO_CRED_CTR'
        },
	'pcie/g/perf/LINK5_COMPLETE_TICKS' : {
		0x00000000ffffffff: 'LINK5_COMPLETE_TICKS'
        },
	'pcie/g/perf/LINK3_REQ_TICKS_MAX' : {
		0x00000000ffffffff: 'LINK3_REQ_TICKS_MAX'
        },
	'pcie/g/perf/LINK10_REQ_TICKS_MAX' : {
		0x00000000ffffffff: 'LINK10_REQ_TICKS_MAX'
        },
	'pcie/g/perf/LINK6_VALID_TICKS' : {
		0x00000000ffffffff: 'LINK6_VALID_TICKS'
        },
	'pcie/g/perf/LINK10_VALID_TICKS' : {
		0x00000000ffffffff: 'LINK10_VALID_TICKS'
        },
	'pcie/g/perf/LINK5_REQ_TICKS_MAX' : {
		0x00000000ffffffff: 'LINK5_REQ_TICKS_MAX'
        },
	'pcie/g/perf/LINK5_REQ_TICKS' : {
		0x00000000ffffffff: 'LINK5_REQ_TICKS'
        },
	'pcie/g/perf/LINK4_REQ_TICKS' : {
		0x00000000ffffffff: 'LINK4_REQ_TICKS'
        },
	'pcie/g/perf/TX_ST_16BYTE_CTR' : {
		0xffffffffffffffff: 'TX_ST_BYTE_CTR'
        },
	'pcie/g/perf/LINK1_REQ_TICKS_MAX' : {
		0x00000000ffffffff: 'LINK1_REQ_TICKS_MAX'
        },
	'pcie/g/perf/LINK9_REQ_TICKS' : {
		0x00000000ffffffff: 'LINK9_REQ_TICKS'
        },
	'pcie/g/perf/LINK11_COMPLETE_TICKS' : {
		0x00000000ffffffff: 'LINK11_COMPLETE_TICKS'
        },
	'pcie/g/perf/LINK1_COMPLETE_TICKS' : {
		0x00000000ffffffff: 'LINK1_COMPLETE_TICKS'
        },
	'pcie/g/perf/LINK9_REQ_TICKS_MAX' : {
		0x00000000ffffffff: 'LINK9_REQ_TICKS_MAX'
        },
	'pcie/g/perf/LINK1_REQ_TICKS' : {
		0x00000000ffffffff: 'LINK1_REQ_TICKS'
        },
	'pcie/g/perf/LINK0_REQ_TICKS' : {
		0x00000000ffffffff: 'LINK0_REQ_TICKS'
        },
	'pcie/g/perf/LINK3_REQ_TICKS' : {
		0x00000000ffffffff: 'LINK3_REQ_TICKS'
        },
	'pcie/g/perf/LINK2_VALID_TICKS' : {
		0x00000000ffffffff: 'LINK2_VALID_TICKS'
        },
	'pcie/g/perf/LINK0_VALID_TICKS' : {
		0x00000000ffffffff: 'LINK0_VALID_TICKS'
        },
	'pcie/g/perf/TX_ST_32BYTE_CTR' : {
		0xffffffffffffffff: 'TX_ST_BYTE_CTR'
        },
	'pcie/g/perf/LINK2_REQ_TICKS_MAX' : {
		0x00000000ffffffff: 'LINK2_REQ_TICKS_MAX'
        },
	'pcie/g/perf/LINK8_REQ_TICKS_MAX' : {
		0x00000000ffffffff: 'LINK8_REQ_TICKS_MAX'
        },
	'pcie/g/perf/Ctrl' : {
		0x0000000000000001: 'LatchCtrs'
        },
	'pcie/g/perf/TX_ST_READY_N_CTR' : {
		0x00000000ffffffff: 'TX_ST_READY_N_CTR'
        },
	'pcie/g/perf/LINK9_VALID_TICKS' : {
		0x00000000ffffffff: 'LINK9_VALID_TICKS'
        },
	'pcie/g/perf/TX_ST_SOP_CTR' : {
		0xffffffffffffffff: 'TX_ST_SOP_CTR'
        },
	'pcie/g/perf/LINK0_COMPLETE_TICKS' : {
		0x00000000ffffffff: 'LINK0_COMPLETE_TICKS'
        },
	'pcie/g/perf/TX_POST_HDR_ZERO_CRED_CTR' : {
		0x000000000000ffff: 'TX_POST_HDR_ZERO_CRED_CTR'
        },
	'pcie/g/perf/LINK6_REQ_TICKS_MAX' : {
		0x00000000ffffffff: 'LINK6_REQ_TICKS_MAX'
        },
	'pcie/g/perf/LINK8_COMPLETE_TICKS' : {
		0x00000000ffffffff: 'LINK8_COMPLETE_TICKS'
        },
	'pcie/g/perf/TX_ST_24BYTE_CTR' : {
		0xffffffffffffffff: 'TX_ST_BYTE_CTR'
        },
	'pcie/g/perf/LINK7_REQ_TICKS' : {
		0x00000000ffffffff: 'LINK7_REQ_TICKS'
        },
	'pcie/g/perf/LINK2_COMPLETE_TICKS' : {
		0x00000000ffffffff: 'LINK2_COMPLETE_TICKS'
        },
	'pcie/g/perf/TX_NON_POST_HDR_ZERO_CRED_CTR' : {
		0x000000000000ffff: 'TX_NON_POST_HDR_ZERO_CRED_CTR'
        },
	'pcie/g/perf/LINK9_COMPLETE_TICKS' : {
		0x00000000ffffffff: 'LINK9_COMPLETE_TICKS'
        },
	'pcie/g/perf/LINK4_REQ_TICKS_MAX' : {
		0x00000000ffffffff: 'LINK4_REQ_TICKS_MAX'
        },
	'pcie/g/perf/LINK10_REQ_TICKS' : {
		0x00000000ffffffff: 'LINK10_REQ_TICKS'
        },
	'pcie/g/perf/LINK7_VALID_TICKS' : {
		0x00000000ffffffff: 'LINK7_VALID_TICKS'
        },
	'pcie/g/perf/LINK11_REQ_TICKS_MAX' : {
		0x00000000ffffffff: 'LINK11_REQ_TICKS_MAX'
        },
	'pcie/g/perf/LINK10_COMPLETE_TICKS' : {
		0x00000000ffffffff: 'LINK10_COMPLETE_TICKS'
        },
	'pcie/g/perf/LINK6_REQ_TICKS' : {
		0x00000000ffffffff: 'LINK6_REQ_TICKS'
        },
	'pcie/g/perf/LINK7_REQ_TICKS_MAX' : {
		0x00000000ffffffff: 'LINK7_REQ_TICKS_MAX'
        },
	'pcie/g/perf/LINK8_VALID_TICKS' : {
		0x00000000ffffffff: 'LINK8_VALID_TICKS'
        },
	'pcie/g/perf/LINK7_COMPLETE_TICKS' : {
		0x00000000ffffffff: 'LINK7_COMPLETE_TICKS'
        },
	'pcie/g/perf/LINK1_VALID_TICKS' : {
		0x00000000ffffffff: 'LINK1_VALID_TICKS'
        },
	'pcie/g/perf/LINK0_REQ_TICKS_MAX' : {
		0x00000000ffffffff: 'LINK0_REQ_TICKS_MAX'
        },
	'pcie/g/perf/LINK3_VALID_TICKS' : {
		0x00000000ffffffff: 'LINK3_VALID_TICKS'
        },
	'pcie/g/perf/TX_NON_POST_DAT_ZERO_CRED_CTR' : {
		0x000000000000ffff: 'TX_NON_POST_DAT_ZERO_CRED_CTR'
        },
	'pcie/g/perf/LINK11_VALID_TICKS' : {
		0x00000000ffffffff: 'LINK11_VALID_TICKS'
        },
	'pcie/g/perf/TICKS_SINCE_LAST_LATCH' : {
		0xffffffffffffffff: 'TICKS_SINCE_LAST_LATCH'
        },
	'pcie/g/perf/LINK11_REQ_TICKS' : {
		0x00000000ffffffff: 'LINK11_REQ_TICKS'
        },
	'pcie/g/perf/LINK4_VALID_TICKS' : {
		0x00000000ffffffff: 'LINK4_VALID_TICKS'
        },
	'pcie/g/perf/_scratch' : {
		0xffffffffffffffff: '_scratch'
        },
	'pcie/g/perf/LINK8_REQ_TICKS' : {
		0x00000000ffffffff: 'LINK8_REQ_TICKS'
        },
	'link/ch/fmac/frame_max' : {
		0x000000000000ffff: 'value'
        },
	'link/ch/fmac/idle_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/efifo_read_level' : {
		0x00000000000000ff: 'value '
        },
	'link/ch/fmac/fmac_err_inj' : {
		0x0000000000000100: 'CRC_err',
		0x00000000000000ff: 'code_viol'
        },
	'link/ch/fmac/data_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/code_viol_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/eof_dec_err_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/fmac_vc_id' : {
		0x000000000000ffff: 'value'
        },
	'link/ch/fmac/invalid_type_err_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/eof_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/r_rdy_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/sof_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/ipg_err_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/efifo_high_limit' : {
		0x00000000000000ff: 'value '
        },
	'link/ch/fmac/fmac_ctl' : {
		0x0000000000000002: 'le_endianess',
		0x0000000000000001: 'crc_disable'
        },
	'link/ch/fmac/pcs_rx_data' : {
		0xffffffffffffffff: 'data'
        },
	'link/ch/fmac/length_err_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/idle_dec_err_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/fmac_vc_sel' : {
		0x0000000000000007: 'value'
        },
	'link/ch/fmac/lr_lrr_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/nos_ols_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/link_up_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/fmac_credit_bbc_max' : {
		0x00000000000003ff: 'value'
        },
	'link/ch/fmac/fmac_debug_0' : {
		0x0000000000000400: 'sm_linkup',
		0x0000000000000380: 'sm_efifo_wr',
		0x0000000000000070: 'sm_efifo_rd',
		0x0000000000000008: 'pcs_valid',
		0x0000000000000004: 'pcs_sync',
		0x0000000000000003: 'pcs_hdr'
        },
	'link/ch/fmac/sync_hdr_err_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/crc_err_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/efifo_delete_cnt' : {
		0x000000000000ffff: 'count'
        },
	'link/ch/fmac/link_down_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/fmac_credit_cnt' : {
		0x00000000000003ff: 'value'
        },
	'link/ch/fmac/fmac_credit_bbc_min' : {
		0x00000000000003ff: 'value'
        },
	'link/ch/fmac/fmac_credit_start' : {
		0x00000000000003ff: 'value'
        },
	'link/ch/fmac/bb_scr_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/efifo_overflow_cnt' : {
		0x000000000000ffff: 'count'
        },
	'link/ch/fmac/efifo_underflow_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/other_dec_err_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/fmac_fifo_status' : {
		0x000000000f800000: 'elastic_fifo_wrusedw',
		0x00000000007c0000: 'elastic_fifo_rdusedw',
		0x0000000000020000: 'elastic_fifo_wr_empty',
		0x0000000000010000: 'elastic_fifo_wr_full',
		0x0000000000008000: 'elastic_fifo_rd_empty',
		0x0000000000004000: 'elastic_fifo_rd_full',
		0x0000000000003c00: 'rcv_fifo_usedw',
		0x0000000000000200: 'rcv_fifo_empty',
		0x0000000000000100: 'rcv_fifo_full',
		0x00000000000000fc: 'fmac_fifo_usedw',
		0x0000000000000002: 'fmac_fifo_empty',
		0x0000000000000001: 'fmac_fifo_full'
        },
	'link/ch/fmac/bad_eof_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/sof_dec_err_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/fmac_time_min_credit' : {
		0x000000000000ffff: 'value'
        },
	'link/ch/fmac/efifo_insert_cnt' : {
		0x000000000000ffff: 'count'
        },
	'link/ch/fmac/fill_word_min' : {
		0x00000000000000ff: 'value'
        },
	'link/ch/fmac/efifo_low_limit' : {
		0x00000000000000ff: 'value '
        },
	'link/ch/fmac/vc_rdy_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/_scratch' : {
		0xffffffffffffffff: 'scratch'
        },
	'link/ch/fmac/bb_scs_cnt' : {
		0x00000000000000ff: 'count'
        },
	'link/ch/fmac/frame_min' : {
		0x000000000000ffff: 'value'
        },
	'pcie/g/csr/gnt_cnt' : {
		0x00000000ffffffff: 'Count'
        },
	'pcie/g/csr/PcieTimeoutPeriod' : {
		0x00000000000fffff: 'PcieTimeoutPeriod'
        },
	'pcie/g/csr/poison_tlp_received_cnt' : {
		0x000000000000ffff: 'poison_tlp_received_cnt'
        },
	'pcie/g/csr/ecc_derr_rpl' : {
		0x000000000000ffff: 'ecc_derr_rpl'
        },
	'pcie/g/csr/dpl_fifo_wrreq_cnt' : {
		0x00000000ffffffff: 'Count'
        },
	'pcie/g/csr/ur_np_tlp_received_cnt' : {
		0x000000000000ffff: 'ur_np_tlp_received_cnt'
        },
	'pcie/g/csr/flush_ctr' : {
		0x0000000e00000000: 'blk_flush_ctr_11',
		0x00000001c0000000: 'blk_flush_ctr_10',
		0x0000000038000000: 'blk_flush_ctr_9',
		0x0000000007000000: 'blk_flush_ctr_8',
		0x0000000000e00000: 'blk_flush_ctr_7',
		0x00000000001c0000: 'blk_flush_ctr_6',
		0x0000000000038000: 'blk_flush_ctr_5',
		0x0000000000007000: 'blk_flush_ctr_4',
		0x0000000000000e00: 'blk_flush_ctr_3',
		0x00000000000001c0: 'blk_flush_ctr_2',
		0x0000000000000038: 'blk_flush_ctr_1',
		0x0000000000000007: 'blk_flush_ctr_0'
        },
	'pcie/g/csr/debug_link_arb' : {
		0x0000000000007f80: 'fifo_used',
		0x0000000000000040: 'link_num_fifo_full',
		0x0000000000000020: 'link_num_fifo_empty',
		0x0000000000000010: 'fifo_empty',
		0x0000000000000008: 'fifo_full',
		0x0000000000000004: 'fifo_blk_avail',
		0x0000000000000003: 'arb_ps'
        },
	'pcie/g/csr/hip_blk_done_cnt' : {
		0x00000000ffffffff: 'Count'
        },
	'pcie/g/csr/PcieRdTimeoutCtr' : {
		0x000000000000ffff: 'PcieRdTimeoutCtr'
        },
	'pcie/g/csr/_scratch' : {
		0xffffffffffffffff: '_scratch'
        },
	'pcie/g/csr/PcieWrTimeoutCtr' : {
		0x000000000000ffff: 'PcieWrTimeoutCtr'
        },
	'pcie/g/csr/dlup_exit_ctr' : {
		0x000000000000ffff: 'dlup_exit_ctr'
        },
	'pcie/g/csr/MaxPyld' : {
		0x0000000000000007: 'size'
        },
	'pcie/g/csr/ur_tlp_received_cnt' : {
		0x000000000000ffff: 'ur_tlp_received_cnt'
        },
	'pcie/g/csr/link_num_fifo_wr_pulse' : {
		0x00000000ffffffff: 'Count'
        },
	'pcie/g/csr/PcieAppCtl' : {
		0x0000000000000001: 'RstPcieRegs'
        },
	'pcie/g/csr/ecc_derr_cor_ext_rpl' : {
		0x000000000000ffff: 'ecc_derr_cor_ext_rpl'
        },
	'pcie/g/csr/serdes_pll_locked_ctr' : {
		0x000000000000ffff: 'serdes_pll_locked_ctr'
        },
	'pcie/g/csr/l2_exit_ctr' : {
		0x000000000000ffff: 'l2_exit_ctr'
        },
	'pcie/g/csr/tx_blk_done_cnt' : {
		0x00000000ffffffff: 'Count'
        },
	'pcie/g/csr/ecc_derr_cor_ext_rcv' : {
		0x000000000000ffff: 'ecc_derr_cor_ext_rcv'
        },
	'pcie/g/csr/FlushStatus' : {
		0x0000000000000fff: 'Done'
        },
	'pcie/g/csr/PcieStatus' : {
		0x0000000000000f00: 'CurrentLanes',
		0x0000000000000030: 'CurrentSpeed',
		0x0000000000000002: 'fixedclk_locked',
		0x0000000000000001: 'serdes_pll_locked'
        },
	'link/ch/mtip_fc1/SofErrCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/mtip_fc1/_scratch' : {
		0xffffffffffffffff: 'scratch'
        },
	'link/ch/mtip_fc1/PrimNosOlsCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/mtip_fc1/InvldErrCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/mtip_fc1/PrimLrLrrCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/mtip_fc1/DispErrCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/mtip_fc1/PrimLinkUpCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/mtip_fc1/PrimLipCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/mtip_fc1/EofErrCtr' : {
		0x00000000ffffffff: 'count'
        },
	'global/g/ucstats/ucstat_le_done_count' : {
		0x00000000ffffffff: 'count'
        },
	'global/g/ucstats/ucstat_data_in' : {
		0x00000000ffffffff: 'data'
        },
	'global/g/ucstats/ucstat_uc_invalid_addr_count' : {
		0x00000000ffffffff: 'count'
        },
	'global/g/ucstats/ucstat_uc_early_done_count' : {
		0x00000000ffffffff: 'count'
        },
	'global/g/ucstats/ucstat_uc_rd_count' : {
		0x00000000ffffffff: 'count'
        },
	'global/g/ucstats/ucstat_uc_done_count' : {
		0x00000000ffffffff: 'count'
        },
	'global/g/ucstats/ucstat_le_req_count' : {
		0x00000000ffffffff: 'count'
        },
	'global/g/ucstats/ucstat_addr' : {
		0x000000000000ffff: 'addr'
        },
	'global/g/ucstats/ucstat_collision_cycle_count' : {
		0x00000000ffffffff: 'count'
        },
	'global/g/ucstats/ucstat_errors' : {
		0x0000000000000002: 'sm_bank_error',
		0x0000000000000001: 'sm_uc_error'
        },
	'global/g/ucstats/ucstat_uc_wr_count' : {
		0x00000000ffffffff: 'count'
        },
	'global/g/ucstats/ucstat_fpga_temp' : {
		0x0000000000000100: 'done',
		0x00000000000000ff: 'temp'
        },
	'global/g/ucstats/ucstat_ctl' : {
		0x0000000000000004: 'tempsense_en',
		0x0000000000000002: 'le_en',
		0x0000000000000001: 'uc_en'
        },
	'global/g/ucstats/ucstat_data_out' : {
		0x00000000ffffffff: 'data'
        },
	'link/ch/extr/DataFrameBpCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/extr/_scratch' : {
		0xffffffffffffffff: '_scratch'
        },
	'link/ch/extr/ExtrEnable' : {
		0x0000000000000001: 'enable'
        },
	'link/ch/extr/DatChnlFifoStat' : {
		0x0000000000020000: 'Underflow',
		0x0000000000010000: 'Overflow',
		0x00000000000003ff: 'Words'
        },
	'link/ch/extr/DatChnlFifoLevel' : {
		0x00000000000003ff: 'count'
        },
	'link/ch/extr/TemplateRam' : {
		0xffffffffffffffff: 'TemplateRam'
        },
	'link/ch/extr/TemplStop' : {
		0x0000000000000008: 'Init',
		0x0000000000000004: 'Overflow',
		0x0000000000000002: 'Ofstorder',
		0x0000000000000001: 'Zerobyte'
        },
	'global/g/fpga/ReconfigStatus' : {
		0x0000000000000020: 'Timeout',
		0x0000000000000010: 'Busy',
		0x000000000000000f: 'Error'
        },
	'global/g/fpga/FpgaRev' : {
		0xffffff0000000000: 'yymmdd',
		0x000000ffffff0000: 'RepoRev',
		0x000000000000ff00: 'Author',
		0x00000000000000ff: 'BitfileRev'
        },
	'global/g/fpga/SFP_LoSig_Force_Value' : {
		0x0000000000ffffff: 'Value'
        },
	'global/g/fpga/IntervalPeriod' : {
		0x000000ffffffffff: 'clocks'
        },
	'global/g/fpga/SFP_LoSig_Force_En' : {
		0x0000000000ffffff: 'En'
        },
	'global/g/fpga/PCIE_Autoreset_Cnt' : {
		0x00000000000000ff: 'reset_count'
        },
	'global/g/fpga/FpgaCap' : {
		0x2000000000000000: 'Lite',
		0x1000000000000000: 'FpgaRightLeft_n',
		0x0e00000000000000: 'DalIdReserved',
		0x0100000000000000: 'DalTopBtm',
		0x0010000000000000: 'BistTx32b',
		0x0008000000000000: 'BistPrbsXcvr',
		0x0004000000000000: 'BistPcie1',
		0x0002000000000000: 'BistPcie0',
		0x0001000000000000: 'Xbar',
		0x0000fff000000000: 'XcvrSpeedMax',
		0x0000000ff0000000: 'NumPcieLanesMax',
		0x000000000f000000: 'PcieGenMax',
		0x0000000000f00000: 'NumPcieEp',
		0x00000000000ff000: 'NumXcvr',
		0x0000000000000f00: 'Protocol',
		0x00000000000000f0: 'NumLinkEngines',
		0x000000000000000f: 'NumDplBuf'
        },
	'global/g/fpga/PCBRev' : {
		0x000000000000000f: 'AssemblyRev'
        },
	'global/g/fpga/FPGA_Ctl' : {
		0x0000000000000020: 'Force_RxData_On_Lossig_Disable',
		0x0000000000000010: 'PCIE_Autoreset_Disable',
		0x0000000000000008: 'LED_Output_Disable',
		0x0000000000000004: 'Logic_Analyzer_Inf_Disable',
		0x0000000000000002: 'Rx_Serdes_Disable',
		0x0000000000000001: 'Tx_Serdes_Disable'
        },
	'global/g/fpga/TimeStamp' : {
		0x00ffffffffffffff: 'Tick'
        },
	'global/g/fpga/_scratch' : {
		0xffffffffffffffff: '_scratch'
        },
	'global/g/fpga/Max_LinkSpeed_Reconfig' : {
		0x00000000ffffffff: 'time'
        },
	'global/g/fpga/ExtIODebug' : {
		0x8000000000000000: 'ioOPT_ROT_2',
		0x4000000000000000: 'ioOPT_ROT_1',
		0x2000000000000000: 'ioOPT_6',
		0x1000000000000000: 'ioOPT_5',
		0x0800000000000000: 'ioOPT_4',
		0x0400000000000000: 'ioOPT_3',
		0x0200000000000000: 'ioOPT_2',
		0x0100000000000000: 'ioOPT_1',
		0x00c0000000000000: 'iBD_NO',
		0x0020000000000000: 'oTXD',
		0x0010000000000000: 'iRXD',
		0x000ffff000000000: 'oLED_N',
		0x0000000800000000: 'iFPGA_ID_N',
		0x0000000780000000: 'iASY',
		0x000000007ff80000: 'oFC_RATE_SEL',
		0x0000000000040000: 'ioEXT4',
		0x0000000000020000: 'ioEXT3',
		0x0000000000010000: 'ioEXT2',
		0x0000000000008000: 'ioEXT1',
		0x0000000000007f80: 'ioFPGA_DATA',
		0x0000000000000060: 'ioBUS_SPARE',
		0x0000000000000010: 'iBUS_MASTER',
		0x0000000000000008: 'iBUS_EN',
		0x0000000000000004: 'iBUS_CLK',
		0x0000000000000002: 'iFPGA_CLRN',
		0x0000000000000001: 'iFPGA_RSTN'
        },
	'global/g/fpga/FpgaDev' : {
		0xffff000000000000: 'Vendor',
		0x0000ff0000000000: 'Family',
		0x000000ff00000000: 'SERDESGrade',
		0x00000000ffffff00: 'Package',
		0x00000000000000ff: 'speedGrade'
        },
	'global/g/fpga/CRC_Error_Message_Register1' : {
		0xffffffffffffffff: 'data'
        },
	'global/g/fpga/CRC_Error_Message_Register0' : {
		0xffffffffffffffff: 'data'
        },
	'global/g/fpga/LoopbackSerdesCfg' : {
		0x0000000000000f00: 'Product',
		0x00000000000000f0: 'Rev',
		0x000000000000000f: 'Mode'
        },
	'global/g/fpga/CRC_Error_Cnt' : {
		0x00000000ffffffff: 'count'
        },
	'global/g/fpga/iSFP_LoSig' : {
		0x0000000000ffffff: 'Value'
        },
	'global/g/fpga/ReconfigCtrl' : {
		0x0000000000000002: 'Direct',
		0x0000000000000001: 'Retry'
        },
	'global/g/fpga/Min_LinkSpeed_Reconfig' : {
		0x00000000ffffffff: 'time'
        },
	'pcie/dplbuf/data/DplBufLastPfn' : {
		0x00000000ffffffff: 'DplBufLastPfn'
        },
	'pcie/dplbuf/data/DplBufRdPtr' : {
		0x00000000ffffffff: 'DplBufRdPtr'
        },
	'pcie/dplbuf/data/_scratch' : {
		0xffffffffffffffff: '_scratch'
        },
	'pcie/dplbuf/data/DplBufStartPfn' : {
		0x00000000ffffffff: 'DplBufStartPfn'
        },
	'pcie/dplbuf/data/DplBufFreePfn' : {
		0x00000000ffffffff: 'DplBufFreePfn'
        },
	'pcie/dplbuf/data/DplBufPtrRst' : {
		0x0000000000000001: 'DplBufPtrRst'
        },
	'pcie/dplbuf/data/DplBufWrPtr' : {
		0x00000000ffffffff: 'DplBufWrPtr'
        },
	'link/ch/ucstats/vendor_oui_sfp_present' : {
		0x00000000ffffff00: 'vendor_oui',
		0x00000000000000ff: 'sfp_present'
        },
	'link/ch/ucstats/vendor_part_number2' : {
		0x00000000ffffffff: 'vendor_pn2'
        },
	'link/ch/ucstats/vendor_part_number3' : {
		0x00000000ffffffff: 'vendor_pn3'
        },
	'link/ch/ucstats/vendor_part_number0' : {
		0x00000000ffffffff: 'vendor_pn0'
        },
	'link/ch/ucstats/vendor_part_number1' : {
		0x00000000ffffffff: 'vendor_pn1'
        },
	'link/ch/ucstats/vendor_revision_number' : {
		0x00000000ffffffff: 'vendor_rn'
        },
	'link/ch/ucstats/vendor_serial_number3' : {
		0x00000000ffffffff: 'vendor_sn3'
        },
	'link/ch/ucstats/vendor_serial_number2' : {
		0x00000000ffffffff: 'vendor_sn2'
        },
	'link/ch/ucstats/vendor_serial_number1' : {
		0x00000000ffffffff: 'vendor_sn1'
        },
	'link/ch/ucstats/vendor_serial_number0' : {
		0x00000000ffffffff: 'vendor_sn0'
        },
	'link/ch/ucstats/SFP_temperature_rate' : {
		0x0000000000ff0000: 'bit_rate',
		0x000000000000ffff: 'temp'
        },
	'link/ch/ucstats/SFP_power' : {
		0x00000000ffff0000: 'tx_power',
		0x000000000000ffff: 'rx_power'
        },
	'link/ch/ucstats/warning' : {
		0x00000000ffffffff: 'flags'
        },
	'link/ch/ucstats/alarm' : {
		0x00000000ffffffff: 'flags'
        },
	'link/ch/mtip_fc2/mtip_debug' : {
		0xfffe000000000000: 'reserved',
		0x0001000000000000: 'rx_class_val',
		0x0000f00000000000: 'rx_class',
		0x0000080000000000: 'rx_end_code_val',
		0x0000078000000000: 'rx_end_code',
		0x0000007ff8000000: 'rx_primitive',
		0x0000000004000000: 'rx_fc1_kchn',
		0x0000000002000000: 'rx_fc1_err',
		0x0000000001000000: 'rx_disp_err',
		0x0000000000800000: 'rx_char_err',
		0x0000000000400000: 'led_link_sync',
		0x0000000000200000: 'led_link_online',
		0x0000000000180000: 'ff_tx_mod',
		0x0000000000040000: 'ff_rx_dsav',
		0x0000000000020000: 'ff_rx_sop',
		0x0000000000010000: 'ff_rx_eop',
		0x0000000000008000: 'ff_rx_err',
		0x0000000000004000: 'ff_rx_rdy',
		0x0000000000002000: 'ff_rx_dval',
		0x0000000000001000: 'comma_det',
		0x0000000000000800: 'rx_phy_los',
		0x0000000000000400: 'scrb_ena',
		0x0000000000000200: 'rx_crc_err',
		0x0000000000000100: 'rx_frm_discard',
		0x0000000000000080: 'rx_length_err',
		0x0000000000000040: 'rx_frm_rcv',
		0x0000000000000020: 'dec_error',
		0x0000000000000010: 'sync_acqurd',
		0x0000000000000008: 'node_off_line',
		0x0000000000000004: 'node_on_line',
		0x0000000000000002: 'node_fault',
		0x0000000000000001: 'node_recovery'
        },
	'link/ch/mtip_fc2/FcLosIErrCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/mtip_fc2/FcEofErrCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/mtip_fc2/SingleStep' : {
		0x0000000080000000: 'mode',
		0x0000000040000000: 'start',
		0x00000000000000ff: 'cnt'
        },
	'link/ch/mtip_fc2/FcFrmCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/mtip_fc2/_scratch' : {
		0xffffffffffffffff: 'scratch'
        },
	'link/ch/mtip_fc2/FcCrcErrCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/mtip_fc2/FcLosErrCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/mtip_fc2/TsFifoStat' : {
		0x0000000000020000: 'Underflow',
		0x0000000000010000: 'Overflow',
		0x000000000000001f: 'Words'
        },
	'link/ch/mtip_fc2/FcTruncErrCtr' : {
		0x00000000ffffffff: 'count'
        },
	'link/ch/mtip_fc2/FramingStop' : {
		0x0000000000000002: 'b2beop',
		0x0000000000000001: 'b2bsop'
        },
	'link/ch/mtip_fc2/FcShortErrCtr' : {
		0x00000000ffffffff: 'count'
        },
	'global/g/xbar/Link2IdleDeleteCnt' : {
		0x000000000000ffff: 'Link2IdleDeleteCnt'
        },
	'global/g/xbar/Link7IdleDeleteCnt' : {
		0x000000000000ffff: 'Link7IdleDeleteCnt'
        },
	'global/g/xbar/Link6IdleDeleteCnt' : {
		0x000000000000ffff: 'Link6IdleDeleteCnt'
        },
	'global/g/xbar/Link12IdleInsertCnt' : {
		0x000000000000ffff: 'Link12IdleInsertCnt'
        },
	'global/g/xbar/Link8IdleInsertCnt' : {
		0x000000000000ffff: 'Link8IdleInsertCnt'
        },
	'global/g/xbar/Link0IdleDeleteCnt' : {
		0x000000000000ffff: 'Link0IdleDeleteCnt'
        },
	'global/g/xbar/Ctl' : {
		0x000000003ffffff0: 'FarLoopbackEn',
		0x0000000000000002: 'IdleType',
		0x0000000000000001: 'SwRst'
        },
	'global/g/xbar/Link5IdleDeleteCnt' : {
		0x000000000000ffff: 'Link5IdleDeleteCnt'
        },
	'global/g/xbar/Link6IdleInsertCnt' : {
		0x000000000000ffff: 'Link6IdleInsertCnt'
        },
	'global/g/xbar/EfifoCtl' : {
		0x0000000fff000000: 'EfifoHighThresh',
		0x0000000000fff000: 'EfifoLowThresh',
		0x0000000000000fff: 'EfifoReadThresh'
        },
	'global/g/xbar/Link11IdleInsertCnt' : {
		0x000000000000ffff: 'Link11IdleInsertCnt'
        },
	'global/g/xbar/Link9IdleInsertCnt' : {
		0x000000000000ffff: 'Link9IdleInsertCnt'
        },
	'global/g/xbar/Link9IdleDeleteCnt' : {
		0x000000000000ffff: 'Link9IdleDeleteCnt'
        },
	'global/g/xbar/Link3IdleInsertCnt' : {
		0x000000000000ffff: 'Link3IdleInsertCnt'
        },
	'global/g/xbar/Cfg' : {
		0x000f000000000000: 'Link12Cfg',
		0x0000f00000000000: 'Link11Cfg',
		0x00000f0000000000: 'Link10Cfg',
		0x000000f000000000: 'Link9Cfg',
		0x0000000f00000000: 'Link8Cfg',
		0x00000000f0000000: 'Link7Cfg',
		0x000000000f000000: 'Link6Cfg',
		0x0000000000f00000: 'Link5Cfg',
		0x00000000000f0000: 'Link4Cfg',
		0x000000000000f000: 'Link3Cfg',
		0x0000000000000f00: 'Link2Cfg',
		0x00000000000000f0: 'Link1Cfg',
		0x000000000000000f: 'Link0Cfg'
        },
	'global/g/xbar/Link0IdleInsertCnt' : {
		0x000000000000ffff: 'Link0IdleInsertCnt'
        },
	'global/g/xbar/Link1IdleDeleteCnt' : {
		0x000000000000ffff: 'Link1IdleDeleteCnt'
        },
	'global/g/xbar/Link4IdleInsertCnt' : {
		0x000000000000ffff: 'Link4IdleInsertCnt'
        },
	'global/g/xbar/Link1IdleInsertCnt' : {
		0x000000000000ffff: 'Link1IdleInsertCnt'
        },
	'global/g/xbar/Link7IdleInsertCnt' : {
		0x000000000000ffff: 'Link7IdleInsertCnt'
        },
	'global/g/xbar/Link10IdleDeleteCnt' : {
		0x000000000000ffff: 'Link10IdleDeleteCnt'
        },
	'global/g/xbar/Link12IdleDeleteCnt' : {
		0x000000000000ffff: 'Link12IdleDeleteCnt'
        },
	'global/g/xbar/EfifoUnderflowStatus' : {
		0x0000000003ffffff: 'Underflow'
        },
	'global/g/xbar/_scratch' : {
		0xffffffffffffffff: '_scratch'
        },
	'global/g/xbar/Link3IdleDeleteCnt' : {
		0x000000000000ffff: 'Link3IdleDeleteCnt'
        },
	'global/g/xbar/Link5IdleInsertCnt' : {
		0x000000000000ffff: 'Link5IdleInsertCnt'
        },
	'global/g/xbar/EfifoOverflowStatus' : {
		0x0000000003ffffff: 'Overflow'
        },
	'global/g/xbar/Link4IdleDeleteCnt' : {
		0x000000000000ffff: 'Link4IdleDeleteCnt'
        },
	'global/g/xbar/Link10IdleInsertCnt' : {
		0x000000000000ffff: 'Link10IdleInsertCnt'
        },
	'global/g/xbar/Link2IdleInsertCnt' : {
		0x000000000000ffff: 'Link2IdleInsertCnt'
        },
	'global/g/xbar/Link11IdleDeleteCnt' : {
		0x000000000000ffff: 'Link11IdleDeleteCnt'
        },
	'global/g/xbar/Link8IdleDeleteCnt' : {
		0x000000000000ffff: 'Link8IdleDeleteCnt'
        }
}



# Standalone Execution
if __name__ == '__main__':
	ERROR = '^[[5;1;31mERROR^[[0m:'
	print "{0} This is not a standalone script, it is used by dal_regs.py".format( ERROR )

