# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/chiwei/work/checkout/fc32.git/xilinx_ip/gtwizard/gtwizard.srcs/sources_1/ip/s5_native_phy_16gbps/s5_native_phy_16gbps.xci
# IP: The module: 's5_native_phy_16gbps' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/gtwizard/gtwizard.srcs/sources_1/ip/s5_native_phy_16gbps/synth/s5_native_phy_16gbps_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 's5_native_phy_16gbps'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/gtwizard/gtwizard.srcs/sources_1/ip/s5_native_phy_16gbps/synth/s5_native_phy_16gbps.xdc
# XDC: The top module name and the constraint reference have the same name: 's5_native_phy_16gbps'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/chiwei/work/checkout/fc32.git/xilinx_ip/gtwizard/gtwizard.srcs/sources_1/ip/s5_native_phy_16gbps/s5_native_phy_16gbps.xci
# IP: The module: 's5_native_phy_16gbps' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/gtwizard/gtwizard.srcs/sources_1/ip/s5_native_phy_16gbps/synth/s5_native_phy_16gbps_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 's5_native_phy_16gbps'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/gtwizard/gtwizard.srcs/sources_1/ip/s5_native_phy_16gbps/synth/s5_native_phy_16gbps.xdc
# XDC: The top module name and the constraint reference have the same name: 's5_native_phy_16gbps'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
