# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/pcie4_uscale_plus_1.xci
# IP: The module: 'pcie4_uscale_plus_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/ip_0/pcie4_uscale_plus_1_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_1_gt || ORIG_REF_NAME==pcie4_uscale_plus_1_gt} -quiet] -quiet

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/pcie4_uscale_plus_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/synth/pcie4_uscale_plus_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/synth/pcie4_uscale_plus_1_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/ip_0/synth/pcie4_uscale_plus_1_gt_ooc.xdc

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/ip_0/synth/pcie4_uscale_plus_1_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_1_gt || ORIG_REF_NAME==pcie4_uscale_plus_1_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/source/ip_pcie4_uscale_plus_x1y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/pcie4_uscale_plus_1.xci
# IP: The module: 'pcie4_uscale_plus_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/ip_0/pcie4_uscale_plus_1_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_1_gt || ORIG_REF_NAME==pcie4_uscale_plus_1_gt} -quiet] -quiet

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/pcie4_uscale_plus_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/synth/pcie4_uscale_plus_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/synth/pcie4_uscale_plus_1_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/ip_0/synth/pcie4_uscale_plus_1_gt_ooc.xdc

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/ip_0/synth/pcie4_uscale_plus_1_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_1_gt || ORIG_REF_NAME==pcie4_uscale_plus_1_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/chiwei/work/checkout/fc32.git/xilinx_ip/pcie4_uscale_plus/pcie_gen3x8.srcs/sources_1/ip/pcie4_uscale_plus_1/source/ip_pcie4_uscale_plus_x1y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
